config/routes.rb
Rails.application.routes.draw do
  resources :users,:only => [:next,:done, :start, :create, :update] do
    member do
      get 'next'
      get 'done'
    end
  end
  root to: 'users#start'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/users/sign_up_step_one.rb
class SignUpStepOne < ActiveType::Record[User]
  has_secure_password
  validates :first_name,:last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  PASSWORD_REQUIREMENT_REGEX = /\A(?=.{8,})
                         (?=.*\d)
                         (?=.*[a-z])
                         /x
  validates :password, format:     { with: PASSWORD_REQUIREMENT_REGEX ,message: "minimum eight characters, at least one letter and one number"}
  validates :password_confirmation, presence: true
end

app/models/users/sign_up_step_two.rb
class SignUpStepTwo < ActiveType::Record[User]
  validates :gender, presence: true
  validates :gender, inclusion: { in: %w(Male Female Non-binary),
                     message: "%{value} is not a valid gender" }
  validates :birthday,:university ,presence: true
  validates :birthday, format: { with: /^\d{4}-\d{2}-\d{2}$/, multiline: true }
  validate :validate_age

  private
  def validate_age
    if birthday.present? && birthday < 150.years.ago.to_date
      errors.add(:birthday, "#{birthday} should be lessthan 150 years old.")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def start
    build_sign_up_step_one
  end

  def create
    build_sign_up_step_one
    save_sign_up_step_one or render 'start'
  end

  def next
    load_sign_up_step_two
    build_sign_up_step_two
  end

  def update
    load_sign_up_step_two
    build_sign_up_step_two
    save_sign_up_step_two or render 'next'
  end

  def done
    load_sign_up_step_two
  end

  private

  def build_sign_up_step_one
    @user ||= sign_up_step_one_scope.build
    @user.attributes = user_params
  end

  def build_sign_up_step_two
    @user ||= sign_up_step_two_scope.build
    @user.attributes = user_params
  end

  def sign_up_step_one_scope
    SignUpStepOne.unscoped
  end

  def sign_up_step_two_scope
    SignUpStepTwo.unscoped
  end

  def user_params
    user_params = params[:user]
    user_params ? user_params.permit(:birthday, :email, :first_name,:gender,:last_name,:university,:password,:password_confirmation) : {}
  end

  def save_sign_up_step_one
    if @user.save
      redirect_to  next_user_path(@user)
    end
  end

  def save_sign_up_step_two
    if @user.save
      flash[:notice] = "User successfully created."
      redirect_to done_user_path(@user)
    end
  end

  def load_sign_up_step_two
    @user ||= sign_up_step_two_scope.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def html_submit(content=fa_icon('save', :text => "Save"), extra={})
    content_tag "button", content.html_safe,  submit_options(extra)
  end

  def submit_options(extra={})
    { "type" => "submit",  "class" => "btn  btn-primary  ", 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i> Please wait...".html_safe }.with_indifferent_access.merge(extra)
  end

  def birthday_format(d)
    d.strftime("#{d.day.ordinalize} %B %Y")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 margin30">
        <div class="footer-col">
          <h3>About Ixperience</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lorem quam, adipiscing condimentum tristique vel, eleifend sed turpis. Pellentesque cursus arcu id magna euismod in elementum purus molestie.
          </p>
          <ul class="list-inline footer-social">
            <li>
              <a href="#" class="social-icon si-dark si-gray-round si-colored-facebook">
                <i class="fa fa-facebook"></i>
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li>
              <a href="#" class="social-icon si-dark si-gray-round si-colored-twitter">
                <i class="fa fa-twitter"></i>
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#" class="social-icon si-dark si-gray-round si-colored-google-plus">
                <i class="fa fa-google-plus"></i>
                <i class="fa fa-google-plus"></i>
              </a>
            </li>
            <li>
              <a href="#" class="social-icon si-dark si-gray-round si-colored-pinterest">
                <i class="fa fa-pinterest"></i>
                <i class="fa fa-pinterest"></i>
              </a>
            </li>
            <li>
              <a href="#" class="social-icon si-dark si-gray-round si-colored-linkedin">
                <i class="fa fa-linkedin"></i>
                <i class="fa fa-linkedin"></i>
              </a>
            </li>
          </ul>
        </div>
      </div><!--footer col-->
      <div class="col-md-3 col-sm-6 margin30">
        <div class="footer-col">
          <h3>Contact</h3>
          <ul class="list-unstyled contact">
            <li><p><strong><i class="fa fa-map-marker"></i> Address:</strong> vaisahali, jaipur, 302012</p></li>
            <li><p><strong><i class="fa fa-envelope"></i> Mail Us:</strong> <a href="#">Support@designmylife.com</a></p></li>
            <li> <p><strong><i class="fa fa-phone"></i> Phone:</strong> +91 1800 2345 2132</p></li>
            <li> <p><strong><i class="fa fa-print"></i> Fax</strong> 1800 2345 2132</p></li>
            <li> <p><strong><i class="fa fa-skype"></i> Skype</strong> Ixperience.856</p></li>
          </ul>
        </div>
      </div><!--footer col-->
      <div class="col-md-3 col-sm-6 margin30">
        <div class="footer-col">
          <h3>Featured Work</h3>
          <ul class="list-inline f2-work">
            <li><a href="portfolio-single.html"><img src="/assets/img/img-1.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-2.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-3.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-4.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-5.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-6.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-7.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-8.jpg" class="img-responsive" alt=""></a></li>
            <li><a href="portfolio-single.html"><img src="/assets/img/img-9.jpg" class="img-responsive" alt=""></a></li>
          </ul>
        </div>
      </div><!--footer col-->
      <div class="col-md-3 col-sm-6 margin30">
        <div class="footer-col">
          <h3>Newsletter</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lorem quam,
          </p>
          <form role="form" class="subscribe-form">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Enter email to subscribe">
              <span class="input-group-btn">
                <button class="btn  btn-theme-dark btn-lg" type="submit">Ok</button>
              </span>
            </div>
          </form>
        </div>
      </div><!--footer col-->

    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <div class="footer-btm">
          <span>&copy;2014. Theme by Design_mylife</span>
        </div>
      </div>
    </div>
  </div>
</footer><!--default footer end here-->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_top_bar_landing_page.html.erb
<!--top-bar start here-->
<div class="top-bar-light">
  <div class="container">
    <div class="row">
      <div class="col-sm-5 hidden-xs">
        <div class="top-bar-socials">
          <a href="#" class="social-icon-sm si-gray si-gray-round si-facebook">
            <i class="fa fa-facebook"></i>
            <i class="fa fa-facebook"></i>
          </a>
          <a href="#" class="social-icon-sm si-gray si-gray-round si-twitter">
            <i class="fa fa-twitter"></i>
            <i class="fa fa-twitter"></i>
          </a>
          <a href="#" class="social-icon-sm si-gray si-gray-round si-g-plus">
            <i class="fa fa-google-plus"></i>
            <i class="fa fa-facebook"></i>
          </a>
          <a href="#" class="social-icon-sm si-gray si-gray-round si-g-plus">
            <i class="fa fa-youtube"></i>
            <i class="fa fa-youtube"></i>
          </a>
          <a href="#" class="social-icon-sm si-gray si-gray-round si-instagram">
            <i class="fa fa-instagram"></i>
            <i class="fa fa-instagram"></i>
          </a>
        </div>
      </div>
      <div class="col-sm-7 text-right">
        <ul class="list-inline top-dark-right">
          <li class="hidden-sm hidden-xs"><i class="fa fa-envelope"></i> Support@Ixperience.com</li>
          <li class="hidden-sm hidden-xs"><i class="fa fa-phone"></i> +01 1800 453 7678</li>
          <li><a href="<%= root_path()%>"><i class="fa fa-user"></i> Sign Up</a></li>
          <li><a class="topbar-icons" href="#"><span><i class="fa fa-search top-search"></i></span></a></li>
        </ul>
        <div class="search">
          <form role="form">
            <input type="text" class="form-control" autocomplete="off" placeholder="Write something and press enter">
            <span class="search-close"><i class="fa fa-times"></i></span>
          </form>
        </div>

      </div>
    </div>
  </div>
</div>
<!--top-bar end here-->

app/views/layouts/_top_landing_navigation.html.erb
<!--navigation -->
<div class="navbar navbar-default navbar-static-top yamm sticky" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <!-- <img src="/assets/img/logo.png" alt="Ixperience"> -->
        <div class="outside">Ixperience</div>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown active ">
          <a href="/" class="dropdown-toggle" >Home <i class=""></i></a>
        </li>
        <!--menu home li end here-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle " data-toggle="dropdown">Portfolio <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu multi-level" role="menu">
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Cube Portfolio </a>
              <ul class="dropdown-menu">
                <li><a href="juicy-portfolio.html"> Juicy Projects</a></li>
                <li><a href="cube-fullwidth.html"> Full Width</a></li>
                <li><a href="cube-masonry.html"> Masonry</a></li>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Grid Text Boxed </a>
              <ul class="dropdown-menu">
                <li><a href="portfolio-2.html"> 2 Columns</a></li>
                <li><a href="portfolio-3.html"> 3 Columns</a></li>
                <li><a href="portfolio-4.html"> 4 Columns</a></li>

              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Grid Boxed </a>
              <ul class="dropdown-menu">
                <li><a href="grid-portfolio-2-no-text.html">2 Columns</a></li>
                <li><a href="grid-portfolio-3-no-text.html">3 Columns</a></li>
                <li><a href="grid-portfolio-4-no-text.html">4 Columns</a></li>

              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">No space Full width </a>
              <ul class="dropdown-menu">
                <li><a href="portfolio-full-width-2.html">2 columns</a></li>
                <li><a href="portfolio-full-width-3.html">3 columns</a></li>
                <li><a href="portfolio-full-width-4.html">4 columns</a></li>
                <li><a href="portfolio-full-width-5.html">5 columns</a></li>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">No Space Boxed </a>
              <ul class="dropdown-menu">
                <li><a href="portfolio-no-space-bx-2.html"> 2 Columns</a></li>
                <li><a href="portfolio-no-space-bx-3.html"> 3 Columns</a></li>
                <li><a href="portfolio-no-space-bx-4.html"> 4 Columns</a></li>

              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Portfolio Masonry </a>
              <ul class="dropdown-menu">
                <li><a href="masonry-portfolio-3.html"> 3 Columns</a></li>
                <li><a href="masonry-portfolio-4.html"> 4 Columns</a></li>
                <li><a href="masonry-portfolio-full.html"> Full Width</a></li>

              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Portfolio Items</a>
              <ul class="dropdown-menu">
                <li><a href="portfolio-single.html">Single item</a></li>
                <li><a href="portfolio-single-2.html">Single item 2</a></li>
              </ul>
            </li>

          </ul>
        </li>
        <!--menu Portfolio li end here-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="blog-full.html">Blog - full width</a></li>
            <li><a href="blog-leftimg.html">Blog - left image</a></li>
            <li><a href="blog-sidebar.html">Blog - sidebar</a></li>
            <li><a href="blog-2col.html">Blog - 2 column</a></li>
            <li><a href="blog-timeline.html">Blog - Timeline</a></li>
            <li><a href="blog-masonary.html">Blog - Masonry</a></li>
            <li><a href="blog-single.html">Blog - Single</a></li>
          </ul>
        </li>
        <!--menu blog li end here-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="about.html">About</a></li>
            <li><a href="me.html">About - Me</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="team.html">Our Team</a></li>
            <li><a href="pricing.html">Our Pricing</a></li>
            <li><a href="faq.html">FAQS</a></li>
            <li><a href="email-template.html">Email Template</a></li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Contact </a>
              <ul class="dropdown-menu">
                <li><a href="contact.html"> Contact default</a></li>
                <li><a href="contact-advanced.php">Contact advanced</a></li>
                <li><a href="contact-option.php">Contact option</a></li>
                <li><a href="contact-flat.php">Contact Flat</a></li>
              </ul>
            </li>
            <li><a href="search-results.html">Search Results</a></li>
            <li><a href="career.html">Career</a></li>
            <li><a href="gallery.html">Gallery</a></li>

            <li><a href="process.html">Our Process</a></li>

          </ul>
        </li>
        <!--menu pages li end here-->

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features  <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu">
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Headers </a>
              <ul class="dropdown-menu">
                <li><a href="index.html">Header 1 - Default</a></li>
                <li><a href="header-dark.html">Header 2 - dark </a></li>
                <li><a href="header-transparent.html">header 3 - transparent </a></li>
                <li><a href="header-center-logo.html">header 4 - Logo center </a></li>
                <li><a href="header-side-panel.html">header 5 - Side panel </a></li>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Footers </a>
              <ul class="dropdown-menu">
                <li><a href="index.html">Footer dark - 1</a></li>
                <li><a href="footer-2.html">Footer dark - 2</a></li>
                <li><a href="footer-3.html">Footer dark - 3 </a></li>
                <li><a href="footer-light-1.html">Footer Light - 1</a></li>
                <li><a href="footer-light-2.html">Footer Light - 2</a></li>
                <li><a href="footer-light-3.html">Footer Light - 3 </a></li>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Page Templates </a>
              <ul class="dropdown-menu">
                <li><a href="full-width.html">Full Width</a></li>
                <li><a href="left-sidebar.html">Left Sidebar</a></li>
                <li><a href="right-sidebar.html">Right sidebar</a></li>
                <li><a href="both-sidebar.html">Both Sidebar</a></li>
                <li><a href="both-right-sidebar.html">Both Right sidebar</a></li>
                <li><a href="both-left-sidebar.html">Both Left Sidebar</a></li>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="#">Coming Soon </a>
              <ul class="dropdown-menu">
                <li><a href="coming-soon-1.html">Coming soon 1</a></li>
                <li><a href="coming-soon-2.html">Coming soon 2</a></li>
                <li><a href="coming-soon-3.html">Coming soon 3</a></li>
              </ul>
            </li>
            <li><a href="side-nav.html">side navigation </a></li>
            <li><a href="maintenance-page.html">Maintenance page </a></li>
            <li><a href="blank.html">Blank Page</a></li>
            <li><a href="error.html">Error - 404</a></li>
            <li><a href="login-ragister.html">Login / Register</a></li>
            <li><a href="login-ragister-classic.html">Login / Register - Classic </a></li>
            <li><a href="invoice.html">Invoice</a></li>
            <li><a href="site-map.html">Site Map</a></li>
          </ul>
        </li><!--features-->

        <!--mega menu-->
        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Shortcodes  <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu">
            <li>
              <div class="yamm-content">
                <div class="row">

                  <div class="col-sm-3">
                    <h3 class="heading">Shortcode 1</h3>
                    <ul class="nav mega-vertical-nav">

                      <li><a href="typography.html"><i class="fa fa-text-height"></i> Typography</a></li>
                      <li><a href="grid-system.html"><i class="fa fa-bars"></i> Grid System</a></li>
                      <li><a href="testimonials.html"><i class="fa fa-comment-o"></i> testimonials </a></li>
                      <li><a href="tabs-accordian.html"><i class="fa fa-table"></i> tabs &  Accordions </a></li>
                    </ul>

                  </div>
                  <div class="col-sm-3">
                    <h3 class="heading">Shortcode 2 </h3>
                    <ul class="nav mega-vertical-nav">
                      <li><a href="buttons.html"><i class="fa fa-cog"></i> Buttons</a></li>
                      <li><a href="social-buttons.html"><i class="fa fa-share"></i> Social Buttons</a></li>
                      <li><a href="alerts.html"><i class="fa fa-bell"></i> Alerts </a></li>
                      <li><a href="other-elements.html"><i class="fa fa-cogs"></i> Other Elements </a></li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h3 class="heading">Shortcode 3</h3>
                    <ul class="nav mega-vertical-nav">
                      <li><a href="font-awesome.html"><i class="fa fa-flag"></i> Font Awesome icons</a></li>
                      <li><a href="pe-icons.html"><i class="pe-7s-like"></i> Pe icons</a></li>
                      <li><a href="carousel-shortcodes.html"><i class="fa fa-sliders"></i> Carousel Sliders </a></li>
                      <li><a href="tables.html"><i class="fa fa-table"></i> Tables </a></li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h3 class="heading">Shortcode 4</h3>
                    <ul class="nav mega-vertical-nav">
                      <li><a href="pricing-tables.html"><i class="fa fa-usd"></i> Pricing tables</a></li>
                      <li><a href="videos.html"><i class="fa fa-image"></i> Responsive videos</a></li>
                      <li><a href="cta.html"><i class="fa fa-map-pin"></i> call to cations </a></li>
                      <li><a href="maps.html"><i class="fa fa-map-marker"></i> Google maps </a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </li> <!--menu Features li end here-->
        <!--mega menu end-->

        <!--                        <li class="dropdown">
        <a href="#" class=" dropdown-toggle" data-toggle="dropdown"><i class="fa fa-lock"></i> Sign In</a>
        <div class="dropdown-menu dropdown-menu-right dropdown-login-box animated fadeInUp">
        <form role="form">
        <h4>Signin</h4>

        <div class="form-group">
        <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <input type="text" class="form-control" placeholder="Username">
      </div>
      <br>
      <div class="input-group">
      <span class="input-group-addon"><i class="fa fa-lock"></i></span>
      <input type="password" class="form-control" placeholder="Password">
    </div>
    <div class="checkbox pull-left">
    <label>
    <input type="checkbox"> Remember me
  </label>
</div>
<a class="btn btn-theme-bg pull-right">Login</a>
<button type="submit" class="btn btn-theme pull-right">Login</button>
<div class="clearfix"></div>
<hr>
<p>Don't have an account! <a href="#">Register Now</a></p>
</div>
</form>
</div>
</li> menu login li end here-->
</ul>
</div><!--/.nav-collapse -->
</div><!--container-->
</div>
<!--navbar-default-->

app/views/layouts/_top_navigator.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
			    <span class="sr-only">Toggle navigation</span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			  </button>
			  <div>Online Battleship</div>
			</div>
      <div id="navbar" class="navbar-collapse collapse">
        <%#= link_to "Logout" ,destroy_player_session_path() , :method=>'delete' ,class: "ng-pristine btn btn-primary ng-scope pull-right" %>
	    </div>
    </div>
  </nav>

app/views/shared/_form_error_messages.html.erb
   <% if  f.object.errors.size > 0 %>
      <div class="alert alert-danger">
        <h4>Please review the problems below:</h4>
        <ul>
          <% f.object.errors.full_messages.each do |e| %>
          <li><%= e %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

app/views/users/done.html.erb
<div class="fieldset">
  <h4>
    User Basic info 
  </h4>
  <dl>
    <dt><span class="label label-info">First Name</span></dt>
    <dd class="well"><%= @user.first_name%></dd>

    <dt><span class="label label-info">Last Name</span></dt>
    <dd class="well"><%= @user.last_name%></dd>

    <dt><span class="label label-info">Email</span></dt>
    <dd class="well"><%= @user.email%></dd>

    <dt><span class="label label-info">Birthday</span></dt>
    <dd class="well"><%= birthday_format @user.birthday %></dd>

    <dt><span class="label label-info">Gender</span></dt>
    <dd class="well"><%= @user.gender %></dd>

    <dt><span class="label label-info">University</span></dt>
    <dd class="well"><%= @user.university %></dd>

  </dl>
</div>

app/views/users/next.html.erb
<%= form_for(@user, url: user_path(@user)) do |form| %>
  <%= render "shared/form_error_messages", f: form%>
  <fieldset>
    <div class="form-group m-b-20">
      <%= form.date_field :birthday, placeholder:"Birthday", class:"form-control input-lg"%>
    </div>

    <div class="form-group m-b-20">
      <%= form.select :gender,%w(Male Female Non-binary) ,placeholder:"Gender", class:"form-control input-lg"%>
    </div>

    <div class="form-group m-b-20">
      <%= form.text_field :university, placeholder:"University.", class:"form-control input-lg"%>
    </div>
  </fieldset>
  <div class="login-buttons">
    <%= html_submit(content=fa_icon('user-plus', :text => "Sign up"), extra={class: "btn btn-success btn-block btn-lg"}) %>
  </div>
<% end %>

app/views/users/start.html.erb
<%= form_for(@user, url: users_path) do |form| %>
  <%= render "shared/form_error_messages", f: form%>
  <fieldset>
    <div class="form-group m-b-20">
      <%= form.text_field :first_name, placeholder:"First Name", class:"form-control input-lg"%>
    </div>

    <div class="form-group m-b-20">
      <%= form.text_field :last_name, placeholder:"Last Name", class:"form-control input-lg"%>
    </div>

    <div class="form-group m-b-20">
      <%= form.email_field :email, autofocus: true , placeholder:"Email Address", class:"form-control input-lg"%>
    </div>

    <div class="form-group m-b-20">
      <%= form.password_field :password,  placeholder:"Password", class:"form-control input-lg"%>
    </div>

    <div class="form-group m-b-20">
      <%= form.password_field :password_confirmation,  placeholder:"Password Confirmation", class:"form-control input-lg"%>
    </div>
  </fieldset>
  <div class="login-buttons">
    <%= html_submit(content=fa_icon('user-plus', :text => "Sign up"), extra={class: "btn btn-success btn-block btn-lg"}) %>
  </div>
<% end %>